version: "3"

services:
  discord-bot:
    container_name: discord-bot
    restart: always
    build: .
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      NODE_ENV: ${NODE_ENV}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      OWNER: ${OWNER}
      DEFAULT_COLOR: ${DEFAULT_COLOR}
      INVITE: ${INVITE}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}

  mysql:
    container_name: mysql
    image: mysql
    restart: always
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: ${DB_HOST}
      MYSQL_USERNAME: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
